// Code generated by himesan; DO NOT EDIT.
// himesan:compiler 0.1.0-dev
// himesan:runtime-abi sando.v1
// himesan:source-sha256 2f04e0f2e6caae73ea3d419a88c53afcaf25d300e76dc522ae2f418a03a68def

package views

import (
	__himesan_context "context"
	__himesan_sando "gamertan.com/sandwich-hime/sando"
	__himesan_io "io"
)

var _ = __himesan_sando.ABI

func Home(view HomeView) __himesan_sando.Component {
	return __himesan_sando.ComponentFunc(func(__himesan_render_context __himesan_context.Context, __himesan_writer __himesan_io.Writer) error {
		_ = __himesan_render_context
//line internal/views/home.sando:5:3
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/views/home.sando:6:37
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n<main id=\"main\" class=\"page\">\n  <p class=\"eyebrow\">"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/views/home.sando:8:26
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (Badge("rendered on this request"))); __himesan_error != nil {
			return __himesan_error
		}
//line internal/views/home.sando:8:62
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</p>\n  <h1>Hello, "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/views/home.sando:9:18
		if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.Visitor)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/views/home.sando:9:33
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, ".</h1>\n  <p class=\"lede\">This page began as readable HTML, became typed Go, and received its data from an ordinary server handler just now.</p>\n\n  <section aria-labelledby=\"trail-heading\">\n    <h2 id=\"trail-heading\">Choose a trail</h2>\n    <div class=\"trail-grid\">\n      "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/views/home.sando:15:10
		for _, trail := range view.Trails {
//line internal/views/home.sando:15:48
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n        <article class=\"trail\">\n          <h3><a href=\""); __himesan_error != nil {
				return __himesan_error
			}
//line internal/views/home.sando:17:28
			if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (trail.URL)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/views/home.sando:17:40
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/views/home.sando:17:46
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (trail.Label)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/views/home.sando:17:60
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</a></h3>\n          <p>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/views/home.sando:18:18
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (trail.Description)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/views/home.sando:18:38
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</p>\n        </article>\n      "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/views/home.sando:20:10
		}
//line internal/views/home.sando:20:14
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n    </div>\n  </section>\n\n  <aside class=\"note\" aria-label=\"Template boundary\">\n    <strong>Two moments, one calm path:</strong> Hime-san generated the component code when the template changed. The compiled application rendered this response with your request data now.\n  </aside>\n</main>\n"); __himesan_error != nil {
			return __himesan_error
		}
		return nil
	})
}
